### ISSUE TITLE
Question about attribute with block

### ISSUE THREAD

**Issue by vladcostea** [pdabrowski6/ironin-interview-task#3]
Hi,

I tried giving it a go and got something working but only after updating post_serializer.rb (I added the block parameter): 
```ruby
attribute :date do |object|
  object.date.strftime("%d-%m-%Y")
end
```

I know the requirements stated to only work in serializer.rb so my question is: is it possible without this modification?

Thanks

**Comment by pdabrowski6** [comment]
@vladcostea it's possible without this modification. When you will collect all attributes and the blocks that are assigned to them (like in the above case), you can execute those blocks in the context of the `object` which is a "something" passed to the serializer.

**Comment by vladcostea** [comment]
Great, thanks!
